name: tailwindcss_build
description: A comprehensive Flutter package that brings the power and convenience of Tailwind CSS utility classes to Flutter development.
version: 0.4.4
homepage: https://github.com/Not996NotOT/tailwindcss_build
repository: https://github.com/Not996NotOT/tailwindcss_build
issue_tracker: https://github.com/Not996NotOT/tailwindcss_build/issues
documentation: https://pub.dev/documentation/tailwindcss_build/latest/

# Publisher information for pub.dev
# publish_to: 默认发布到 pub.dev

# Package metadata
topics:
  - tailwindcss
  - flutter
  - ui
  - utility-classes
  - widgets

# Funding (optional)
funding:
  - https://github.com/sponsors/Not996NotOT

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Flutter specific configuration
flutter:

# 平台支持配置
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
